[package]
name = "aquila_core"
version = "0.1.0"
edition = "2024"


[dependencies]
serde = { workspace = true }
bytes = {workspace = true}
chrono = {workspace = true}
serde_json = {workspace = true}
thiserror = "2.0"